"""Initial schema with profiles, imagebuilders, builds, artifacts, and flash_records

Revision ID: 164336717196
Revises:
Create Date: 2025-11-28 19:45:58.891920

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "164336717196"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imagebuilders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("openwrt_release", sa.String(length=50), nullable=False),
        sa.Column("target", sa.String(length=100), nullable=False),
        sa.Column("subtarget", sa.String(length=100), nullable=False),
        sa.Column("upstream_url", sa.String(length=1000), nullable=False),
        sa.Column("archive_path", sa.String(length=500), nullable=True),
        sa.Column("root_dir", sa.String(length=500), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("first_used_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_imagebuilders_openwrt_release"),
        "imagebuilders",
        ["openwrt_release"],
        unique=False,
    )
    op.create_index(
        "ix_imagebuilders_release_target_subtarget",
        "imagebuilders",
        ["openwrt_release", "target", "subtarget"],
        unique=True,
    )
    op.create_index(
        op.f("ix_imagebuilders_subtarget"), "imagebuilders", ["subtarget"], unique=False
    )
    op.create_index(
        op.f("ix_imagebuilders_target"), "imagebuilders", ["target"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("device_id", sa.String(length=255), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("openwrt_release", sa.String(length=50), nullable=False),
        sa.Column("target", sa.String(length=100), nullable=False),
        sa.Column("subtarget", sa.String(length=100), nullable=False),
        sa.Column("imagebuilder_profile", sa.String(length=255), nullable=False),
        sa.Column("packages", sa.JSON(), nullable=True),
        sa.Column("packages_remove", sa.JSON(), nullable=True),
        sa.Column("files", sa.JSON(), nullable=True),
        sa.Column("overlay_dir", sa.String(length=500), nullable=True),
        sa.Column("policies", sa.JSON(), nullable=True),
        sa.Column("build_defaults", sa.JSON(), nullable=True),
        sa.Column("bin_dir", sa.String(length=500), nullable=True),
        sa.Column("extra_image_name", sa.String(length=255), nullable=True),
        sa.Column("disabled_services", sa.JSON(), nullable=True),
        sa.Column("rootfs_partsize", sa.Integer(), nullable=True),
        sa.Column("add_local_key", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_profiles_device_id"), "profiles", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_profiles_openwrt_release"),
        "profiles",
        ["openwrt_release"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profiles_profile_id"), "profiles", ["profile_id"], unique=True
    )
    op.create_index(
        "ix_profiles_release_target",
        "profiles",
        ["openwrt_release", "target", "subtarget"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profiles_subtarget"), "profiles", ["subtarget"], unique=False
    )
    op.create_index(op.f("ix_profiles_target"), "profiles", ["target"], unique=False)
    op.create_table(
        "build_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("imagebuilder_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("input_snapshot", sa.JSON(), nullable=True),
        sa.Column("cache_key", sa.String(length=128), nullable=False),
        sa.Column("build_dir", sa.String(length=500), nullable=True),
        sa.Column("log_path", sa.String(length=500), nullable=True),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("is_cache_hit", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["imagebuilder_id"],
            ["imagebuilders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_build_records_cache_key"), "build_records", ["cache_key"], unique=False
    )
    op.create_index(
        op.f("ix_build_records_imagebuilder_id"),
        "build_records",
        ["imagebuilder_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_build_records_profile_id"),
        "build_records",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        "ix_build_records_profile_status",
        "build_records",
        ["profile_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_build_records_status"), "build_records", ["status"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=True),
        sa.Column("relative_path", sa.String(length=500), nullable=False),
        sa.Column("absolute_path", sa.String(length=500), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["build_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifacts_build_id"), "artifacts", ["build_id"], unique=False
    )
    op.create_index(op.f("ix_artifacts_kind"), "artifacts", ["kind"], unique=False)
    op.create_table(
        "flash_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("artifact_id", sa.Integer(), nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("device_path", sa.String(length=100), nullable=False),
        sa.Column("device_model", sa.String(length=255), nullable=True),
        sa.Column("device_serial", sa.String(length=255), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("wiped_before_flash", sa.Boolean(), nullable=False),
        sa.Column("verification_mode", sa.String(length=20), nullable=True),
        sa.Column("verification_result", sa.String(length=20), nullable=True),
        sa.Column("log_path", sa.String(length=500), nullable=True),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["build_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flash_records_artifact_id"),
        "flash_records",
        ["artifact_id"],
        unique=False,
    )
    op.create_index(
        "ix_flash_records_artifact_status",
        "flash_records",
        ["artifact_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flash_records_build_id"), "flash_records", ["build_id"], unique=False
    )
    op.create_index(
        op.f("ix_flash_records_device_path"),
        "flash_records",
        ["device_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flash_records_status"), "flash_records", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flash_records_status"), table_name="flash_records")
    op.drop_index(op.f("ix_flash_records_device_path"), table_name="flash_records")
    op.drop_index(op.f("ix_flash_records_build_id"), table_name="flash_records")
    op.drop_index("ix_flash_records_artifact_status", table_name="flash_records")
    op.drop_index(op.f("ix_flash_records_artifact_id"), table_name="flash_records")
    op.drop_table("flash_records")
    op.drop_index(op.f("ix_artifacts_kind"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_build_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_build_records_status"), table_name="build_records")
    op.drop_index("ix_build_records_profile_status", table_name="build_records")
    op.drop_index(op.f("ix_build_records_profile_id"), table_name="build_records")
    op.drop_index(op.f("ix_build_records_imagebuilder_id"), table_name="build_records")
    op.drop_index(op.f("ix_build_records_cache_key"), table_name="build_records")
    op.drop_table("build_records")
    op.drop_index(op.f("ix_profiles_target"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_subtarget"), table_name="profiles")
    op.drop_index("ix_profiles_release_target", table_name="profiles")
    op.drop_index(op.f("ix_profiles_profile_id"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_openwrt_release"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_device_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_imagebuilders_target"), table_name="imagebuilders")
    op.drop_index(op.f("ix_imagebuilders_subtarget"), table_name="imagebuilders")
    op.drop_index(
        "ix_imagebuilders_release_target_subtarget", table_name="imagebuilders"
    )
    op.drop_index(op.f("ix_imagebuilders_openwrt_release"), table_name="imagebuilders")
    op.drop_table("imagebuilders")
    # ### end Alembic commands ###
